version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-volume:/data/db

  mysql:
    image: mysql
    environment:
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
    - "3306:3306"

  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"

  log-server:
    image: sshtel/log-server
    ports:
      - 8080:8080
    environment:
      - CONFIG_MONGO=/app/configs/mongo.json
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
